### ISSUE TITLE
Unable to find an entry point named 'LhInstallHook' in DLL 'corehook32.dll'

### ISSUE THREAD

**Issue by Trojaner25** [unknownv2/CoreHook#13]
I have renamed the easyhook dll to corehook32 as it stated on CoreHook.Hooking repository.

```
System.EntryPointNotFoundException: Unable to find an entry point named 'LhInstallHook' in DLL 'corehook32.dll'.
    at CoreHook.LocalHook.Create(IntPtr InTargetProc, Delegate InNewProc, Object InCallback) 
```

Happens at:
```cs
var hook = LocalHook.Create(originalMethodAddress, _callback, null);
```

**Comment by Trojaner25** [comment]
Updating to latest EasyHook dlls fixed the issue

**Comment by unknownv2** [comment]
That's good to hear, I've also added a pre-release for the binaries for CoreHook.Hooking here while I'm still working on getting the project to NuGet: 

https://github.com/unknownv2/CoreHook.Hooking/releases/tag/0.0.1
