### ISSUE TITLE
Easier usage via NuGet?

### ISSUE THREAD

**Issue by alexrp** [unknownv2/CoreHook#135]
Hello,

I am currently using EasyHook for two of my projects. I'd like to migrate both to .NET Core, so I'm considering CoreHook.

A really nice thing about EasyHook is that its NuGet package contains everything you need, including the unmanaged libraries required for injection and hosting. This means that all you have to do is reference the NuGet package and those dependencies will all get copied to your build output directory. You can then use `RemoteHooking.Inject(...)` and everything just works; there's no need to manually download and unzip any archives (as is required for `CoreHook.Host`).

Here's an example of how I'm using EasyHook in practice, in case it's relevant:

* https://github.com/tera-alkahest/alkahest/blob/master/Alkahest/Alkahest.csproj#L29
* https://github.com/tera-alkahest/alkahest/blob/master/Alkahest/Commands/ScanCommand.cs
* https://github.com/tera-alkahest/alkahest/tree/master/Alkahest/Scanner/EntryPoint.cs

Would it be possible to make the CoreHook NuGet package similarly easy to consume?

**Comment by unknownv2** [comment]
There's no on-going development for this project anymore, but it might be possible to write a PowerShell script to replicate that functionality.
