### ISSUE TITLE
The UWP example doesn't work

### ISSUE THREAD

**Issue by UlyssesWu** [unknownv2/CoreHook#17]
Hi,

I tested the CoreHook.UWP.FileMonitor but it doesn't work. Am I doing something wrong?

When I launch (with admin privilege) `dotnet CoreHook.UWP.FileMonitor.dll Microsoft.WindowsCalculator_8wekyb3d8bbwe!App`, the calculator launched but then freezed, and after some time, an exception threw and then the calculator terminated.
Also tried to launch `Microsoft.MinecraftUWP_8wekyb3d8bbwe!App` but also freezed. When launch without admin privilege, the UWP won't freeze or close but same exception throws.

```
Unhandled Exception: System.TimeoutException: Unable to wait for injection completion.
   at CoreHook.ManagedHook.Remote.InjectionHelper.WaitForInjection(Int32 InTargetPID) in D:\Documents\Visual Studio 2017\Projects\CoreHook\CoreHook.ManagedHook\Remote\InjectionLoader.cs:line 110
   at CoreHook.ManagedHook.Remote.RemoteHooking.InjectEx(Int32 hostPID, Int32 targetPID, Int32 wakeUpTID, String lbraryPath_x86, String libraryPath_x64, Boolean InCanBypassWOW64, String coreRunDll, String coreLoadDll, String coreClrPath, String coreLibrariesPath, IPipePlatform pipePlatform, IEnumerable`1 dependencies, Object[] InPassThruArgs) in D:\Documents\Visual Studio 2017\Projects\CoreHook\CoreHook.ManagedHook\Remote\RemoteHooking.cs:line 221
...
```

OS: Windows 10 Pro 17134
.NET Core: 2.1.2
Environment Vars: `CORE_LIBRARIES` and `CORE_ROOT` set to `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.2`
Both `corehook64.dll` and `CoreRunDLL64.dll` are put in the same directory as `CoreHook.UWP.FileMonitor.dll`

**Comment by unknownv2** [comment]
It looks like this is a problem with how the dependencies for CoreHook.CoreLoad are copied to the folder. I need to find a way to copy them to the UWP build directory as well or just use the same output directory for all of them. 

 The dependencies for CoreLoad are :
     
     Newtonsoft.Json.dll
     Microsoft.Extensions.DependencyModel.dll
     Microsoft.DotNet.PlatformAbstractions.dll

Right now, you can copy the dlls you see in the regular Win32 CoreHook (.netcoreapp2.1 folder) build folder to the UWP build directory.

For example:
Win32 path: CoreHook\Build\bin\Debug\netcoreapp2.1
UWP path: CoreHook\Examples\UWP\Build\bin\Debug\netcoreapp2.1

Copy the files starting with Microsoft.DotNet.PlatformAbstractions.dll and ending with System.Threading.dll (15 files total).

Thank you very much for reporting this, I will work on fixing this problem.

**Comment by unknownv2** [comment]
Alright, that's unfortunate. so let's see if we can try and figure out what's going on.

Does the Win32 version work for you?

**Comment by UlyssesWu** [comment]
I can use the Win32 version, although it shows some log like this (but still works):

```
OnNewConnection caught IO exception, exiting process
Press Enter to quit.
Connection received from pipe CoreHook
```

**Comment by unknownv2** [comment]
Do you have any tools you can use (for example: https://processhacker.sourceforge.io/) to check the list of loaded modules(DLLs) in the UWP process? We can see what was loaded to tell how far the process gets.

**Comment by UlyssesWu** [comment]
Since the UWP exits soon after injection, I tried a few times and managed to get a screenshot here:
![corehook_calc_modules](https://user-images.githubusercontent.com/4312781/43693510-dfcf3636-9960-11e8-8c35-4429c0819d53.jpg)

**Comment by UlyssesWu** [comment]
That's something I don't really good at... All I know is that it's some kind of `Access violation`:

(53f4.6364): Access violation - code c0000005 (first chance)
(trying to read 0x0000000000000000)

**Comment by unknownv2** [comment]
Alright, no problem. Windows makes it easy to collect crash dumps.

Try following this tutorial:

https://docs.microsoft.com/en-us/windows/desktop/wer/collecting-user-mode-dumps

It will create dumps when applications crash (default folder: %LOCALAPPDATA%\CrashDumps).

You can then open the "*.DMP" file it creates to see where the crash was.

**Comment by UlyssesWu** [comment]
I copied those files but no luck... Then I copied all files (no overwrite) - still no luck. The exception is same as before.

I don't know if this info from WinDbg helps:

```
Loading unloaded module list
.......
WARNING: Teb 27 pointer is NULL - defaulting to 00000000`7ffde000
WARNING: 00000000`7ffde000 does not appear to be a TEB
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(3a00.4f68): CLR exception - code e0434352 (first/second chance not available)
WARNING: Thread 4f68 access failure during dump writing, NTSTATUS 0xC0000022
WARNING: Teb 27 pointer is NULL - defaulting to 00000000`7ffde000
WARNING: 00000000`7ffde000 does not appear to be a TEB
WARNING: Teb 27 pointer is NULL - defaulting to 00000000`7ffde000
WARNING: 00000000`7ffde000 does not appear to be a TEB
00000000`00000000 ??              ???
0:027> .ecxr
rax=00007ff86b5e6713 rbx=0000000000000001 rcx=00007ff90f3dc956
rdx=0000000a0000000a rsi=0000000000000005 rdi=000001b9fd087768
rip=00007ff924caa388 rsp=0000007d763ff260 rbp=0000007d763ff6c0
 r8=0000000000000000  r9=00000000000000a0 r10=0000000000000000
r11=00007ff90f3d8029 r12=000001b9fd087760 r13=0000000000000008
r14=00000000e0434352 r15=0000007d763ff418
iopl=0         nv up ei pl nz na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000206
KERNELBASE!RaiseException+0x68:
00007ff9`24caa388 488b8c24c0000000 mov     rcx,qword ptr [rsp+0C0h] ss:0000007d`763ff320=00001dda1853632e
```

**Comment by unknownv2** [comment]
Can you enter "k" in WinDbg and paste the call stack?

If possible as well, you can send the crash dump to my email at thierry44[at]gmail[dot]com

**Comment by UlyssesWu** [comment]
Thanks, I will send you the dump files...

```
0:030> k
WARNING: Teb 30 pointer is NULL - defaulting to 00000000`7ffde000
WARNING: 00000000`7ffde000 does not appear to be a TEB
 # Child-SP          RetAddr           Call Site
00 00000000`00000000 00000000`00000000 0x0

```

**Comment by unknownv2** [comment]
Looks like the JsonRpc DLLs weren't loaded in that dump. Can you right click on the files and check if they have the "ALL APPLICATION PACKAGES" user under the Security tab?

They should be in the UWP netcoreapp2.1 folder and the netstandard2.0 folder as well.

**Comment by UlyssesWu** [comment]
Yes they already have.

**Comment by unknownv2** [comment]
Alright, can you open your Visual Studio and take a look at the Nuget dependencies tree for the CoreHook.DependencyModel project file? Expand the tree for Dependencies->Nuget->Microsoft.Extensions.DependencyModel and tell me what version of Newtonsoft.Json.dll it references.

**Comment by UlyssesWu** [comment]
CoreHook.DependencyModel -> Microsoft.Extensions.DependencyModel (2.1.0) -> Newtonsoft.Json (9.0.1)

The Newtonsoft.Json.dll in netcoreapp2.1 (and netstandard2.0) folder is v11.0.2.

**Comment by unknownv2** [comment]
Try removing the Microsoft.Extensions.DependencyModel.dll reference, then install Newtonsoft.Json.dll v11.0.2 and re-install the Microsoft.Extensions.DependencyModel using nuget and let me know if that works.

**Comment by unknownv2** [comment]
Hey @UlyssesWu ,

I have made more changes and updated the code to the repository so that hopefully it fixes the errors you have. Try checkout out the repo again and building the code. You can also build [CoreHook.Host] (https://github.com/unknownv2/CoreHook.Host/) which will give you debug symbols for corerundll64.dll in case that helps.

Please let me know if the updated version works now.

**Comment by UlyssesWu** [comment]
I have to say it's hard for me to compile these dependencies...

When compiling `CoreHook.Hooking`, I got an error `U1073 Dont know how to make "..\..\lib.X64\syelog.lib"`. I fixed this by compiling samples first.

When compiling `CoreHook.Host`, the compilation failed because there is no `clretwallmain.h` on my computer. I don't know how to get it - maybe clone coreclr repo? I have to use the binary in release (v0.0.4).

The result is, it no longer freezes or crashes the UWP app, but the injection still fails due to TimeOutException.

**Comment by unknownv2** [comment]
Alright, thank you, I understand it can be somewhat rough compiling everything and I am working on making it easier to build using solutions. I am working on a Visual Studio solution for CoreHook.Hooking and will take a look at CoreHook.Host to fix that error. Thank you again for letting me know, I appreciate the reports a great deal!

I will also work on adding a logger for initial loading steps so that it outputs to a named pipe for error messages and progress so we can see where it stops.

Just to check, did you update your environment variables as well from the old ones  as shown [here](https://github.com/unknownv2/CoreHook#windows) to separate x86 and x64?

**Comment by UlyssesWu** [comment]
Yes I'm using the new style env vars.
![system_env](https://user-images.githubusercontent.com/4312781/45011880-63e63d00-b047-11e8-8fb8-155a5c85c9e1.png)

**Comment by unknownv2** [comment]
Thank you for checking!

Checkout the Visual Studio solution the Hooking module [here](https://github.com/unknownv2/CoreHook.Hooking/tree/master/vs) and let me know if that compiles please.

**Comment by UlyssesWu** [comment]
Yes, it compiles. (And the test result is still the same.)

**Comment by unknownv2** [comment]
Thank you again! I will work on that logger and give you an update when it's ready to test!

I've also updated the [Host](https://github.com/unknownv2/CoreHook.Host). It did not commit the folder with that missing header since it was in a "obj" header and the gitignore file meant it wasn't being tracked. Let me know if that compiles for you now.

Thank you!

**Comment by UlyssesWu** [comment]
Yes, it also compiles now. (And the test result is also the same 😎 )

**Comment by unknownv2** [comment]
Thank you so much for doing the builds!!!

The logger shouldn't take too long, so I will ping you here in the next couple days!

**Comment by unknownv2** [comment]
Hi @UlyssesWu,

Can you check out these two branches (branch name 'pipe-log') for the [Host](https://github.com/unknownv2/CoreHook.Host/tree/pipe-log) and [CoreHook](https://github.com/unknownv2/CoreHook/tree/pipe-log).

They should print more messages while loading the Hook example and any exceptions that occur during the load, and if you can, please post all of the output you receive.

Thank you!

**Comment by UlyssesWu** [comment]
I built both project on `pipe-log` branch (Debug, AnyCPU/x64), but... there was no additional messages appeared? It just shows the expection info like before...

**Comment by unknownv2** [comment]
It should print messages with strings like “HostLog”, make sure you rebuild each project and replace the corerundll64. Can you post the logs from your console?

**Comment by unknownv2** [comment]
The native dlls should be in the x64 folder and not the netstandard2.0 folder, so try placing them there since it looks like corerundll64 is not being injected.

**Comment by UlyssesWu** [comment]
I already put the native dlls in `x64` folder. I just had another (old) copy in `netstandard2.0` folder but I have removed them.

**Comment by unknownv2** [comment]
Alright, since you have the Debug versions available for the corerundll64: Try starting the Calculator application, then attach to the Calculator process with Visual Studio. Open the "corerundll.cpp" file and set a breakpoint on the "LoadAssembly" and "ExecuteAssemblyFunction" functions in "corerundll.cpp", and start the UWP FileMonitor with the process id, then step through the process and see if it tells you where it fails.

Also, try deleting the repository and re-building from scratch.

**Comment by unknownv2** [comment]
Seems like an issue with the pipe connection then. Check the “Output” tab in Visual Studio debugger when you are attached to the Calculator process and send what is written in there.

**Comment by UlyssesWu** [comment]
I think there is no log written by your logger either, just VS normal logs... however I will check again and send them when I have time.

**Comment by unknownv2** [comment]
It should print "Adding hook to kernelbase!CreateFile2" if it gets to the hooking function but otherwise, it will not at the moment. I will add better logging and write to a file instead as well so it's easier to track.

**Comment by UlyssesWu** [comment]
Output log in VS:

```
Starting pipe client...
Attempting to connect to the server pipe
Exception at 0x00007FFBA4CFA388 (KernelBase.dll) in Calculator.exe: 0xE0434352 (parameters: 0xFFFFFFFF80070005, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFCB61A0000).
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at CoreHook.IPC.NamedPipes.NamedPipeClient.Connect(Int32 timeoutMilliseconds)
   at CoreHook.CoreLoad.Loader.Load(String paramPtr)
```

Besides, you should add `"` for paths in post-build events (`CoreHook` project) or it always fails when building in a path contains `Visual Studio 2017`.

```
copy "$(TargetDir)$(TargetFileName)" "$(OutDir)..\x86\$(TargetFileName)"
...
```

**Comment by unknownv2** [comment]
Perfect, thank you. Looks like a access pipe issue, so I updated the UWP pipe access code. Try pulling latest changes and try again.

I will also go ahead and add that path fix!

**Comment by UlyssesWu** [comment]
I think we finally solved this issue: The lastest code works on my PC now! (Calculator doesn't load any files so I tried on Minecraft and it works very well.)

Thank you very much!!

**Comment by unknownv2** [comment]
That's great to hear!!

Thank you for being patient and working together to get it resolved. I hope you have a fun time playing with the library!
